image: node:18

stages:
  - test

cache:
  paths:
    - tc/node_modules/

test:
  stage: test
  script:
    - cd tc
    - npm install
    - npx vitest run
  artifacts:
    paths:
      - tc/test-results/
    when: always
  only:
    - lab5